fix for: java.lang.NullPointerException: Attempt to get length of null array
HowTo reproduce:
0) set flag don’t keep activities to true(in developers settings)
1) open any number picker
2) press home button
3) open app again
crash logs:
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.codetroopers.betterpickersapp/com.codetroopers.betterp
ickers.sample.activity.numberpicker.SampleNumberBasicUsage}:
java.lang.NullPointerException: Attempt to get length of null array

             at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:241
6)

             at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476
)

             at android.app.ActivityThread.-wrap11(ActivityThread.java)

             at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)

             at android.os.Handler.dispatchMessage(Handler.java:102)

             at android.os.Looper.loop(Looper.java:148)

             at
android.app.ActivityThread.main(ActivityThread.java:5417)

             at java.lang.reflect.Method.invoke(Native Method)

             at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:726)

             at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

          Caused by: java.lang.NullPointerException: Attempt to get
length of null array

             at android.os.Parcel.readIntArray(Parcel.java:921)

             at
com.codetroopers.betterpickers.numberpicker.NumberPicker$SavedState.<ini
t>(NumberPicker.java:607)

             at
com.codetroopers.betterpickers.numberpicker.NumberPicker$SavedState.<ini
t>(NumberPicker.java:592)

             at
com.codetroopers.betterpickers.numberpicker.NumberPicker$SavedState$1.cr
eateFromParcel(NumberPicker.java:629)

             at
com.codetroopers.betterpickers.numberpicker.NumberPicker$SavedState$1.cr
eateFromParcel(NumberPicker.java:627)

             at android.os.Parcel.readParcelable(Parcel.java:2367)

             at android.os.Parcel.readValue(Parcel.java:2264)

             at
android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)

             at android.os.Parcel.readSparseArray(Parcel.java:1967)

             at android.os.Parcel.readValue(Parcel.java:2321)

             at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)

             at android.os.BaseBundle.unparcel(BaseBundle.java:221)

             at
android.os.Bundle.getSparseParcelableArray(Bundle.java:856)

             at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.j
ava:997)

             at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.j
ava:1248)

             at
android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.j
ava:1230)

             at
android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManage
r.java:2037)

             at
android.support.v4.app.FragmentController.dispatchCreate(FragmentControl
ler.java:154)

             at
android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:2
89)

             at
android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java
:61)

             at
com.codetroopers.betterpickers.sample.activity.BaseSampleActivity.onCrea
te(BaseSampleActivity.java:11)

             at
com.codetroopers.betterpickers.sample.activity.numberpicker.SampleNumber
BasicUsage.onCreate(SampleNumberBasicUsage.java:26)

             at android.app.Activity.performCreate(Activity.java:6251)

             at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:11
07)

             at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:236
9)

             at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476
) 

             at android.app.ActivityThread.-wrap11(ActivityThread.java) 

             at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 

             at android.os.Handler.dispatchMessage(Handler.java:102) 

             at android.os.Looper.loop(Looper.java:148) 

             at
android.app.ActivityThread.main(ActivityThread.java:5417) 

             at java.lang.reflect.Method.invoke(Native Method) 

             at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:726) 

             at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 